version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongoinsta
    ports:
      - "27017:27017"
    volumes:
      - $HOME/DOCKER_VOLUME/mongo-insta/data:/data/db
  app:
    restart: always
    container_name: insta_todo
    environment:
      NODE_ENV: development
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongo
    ports:
      - "9000:8080"
